/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */

namespace jangi
{
  public enum JgC2S_Msgs
  {
    kUnknown = 0,
    kLogin = 1,
    kChannelInfo = 2,
    kReqMatch = 3,
    kReqCancelMatch = 4,
    kSangcharim = 5,
    kMovePawn = 6,
    kPassTurn = 7,
  }
}
