/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */

namespace jangi
{
  public enum JgS2C_Msgs
  {
    kUnknown = 0,
    kNtfTestString = 1,
    kLogin = 2,
    kChannelInfo = 3,
    kNtfMatch = 4,
    kCancelMatch = 5,
    kNtfSangcharimHan = 6,
    kNtfSangcharim = 7,
    kNtfChangeTurn = 8,
    kNtfMovePawn = 9,
  }
}
