/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;
using System.IO;
using Thrift;
using Thrift.Collections;
using System.Runtime.Serialization;
using Thrift.Protocol;
using Thrift.Transport;

namespace jangi
{

  #if !SILVERLIGHT
  [Serializable]
  #endif
  public partial class NtfSangcharimHan : TBase
  {
    private Sangcharim _han;

    /// <summary>
    /// 
    /// <seealso cref="Sangcharim"/>
    /// </summary>
    public Sangcharim Han
    {
      get
      {
        return _han;
      }
      set
      {
        __isset.han = true;
        this._han = value;
      }
    }


    public Isset __isset;
    #if !SILVERLIGHT
    [Serializable]
    #endif
    public struct Isset {
      public bool han;
    }

    public NtfSangcharimHan() {
    }

    public void Read (TProtocol iprot)
    {
      iprot.IncrementRecursionDepth();
      try
      {
        TField field;
        iprot.ReadStructBegin();
        while (true)
        {
          field = iprot.ReadFieldBegin();
          if (field.Type == TType.Stop) { 
            break;
          }
          switch (field.ID)
          {
            case 1:
              if (field.Type == TType.I32) {
                Han = (Sangcharim)iprot.ReadI32();
              } else { 
                TProtocolUtil.Skip(iprot, field.Type);
              }
              break;
            default: 
              TProtocolUtil.Skip(iprot, field.Type);
              break;
          }
          iprot.ReadFieldEnd();
        }
        iprot.ReadStructEnd();
      }
      finally
      {
        iprot.DecrementRecursionDepth();
      }
    }

    public void Write(TProtocol oprot) {
      oprot.IncrementRecursionDepth();
      try
      {
        TStruct struc = new TStruct("NtfSangcharimHan");
        oprot.WriteStructBegin(struc);
        TField field = new TField();
        if (__isset.han) {
          field.Name = "han";
          field.Type = TType.I32;
          field.ID = 1;
          oprot.WriteFieldBegin(field);
          oprot.WriteI32((int)Han);
          oprot.WriteFieldEnd();
        }
        oprot.WriteFieldStop();
        oprot.WriteStructEnd();
      }
      finally
      {
        oprot.DecrementRecursionDepth();
      }
    }

    public override string ToString() {
      StringBuilder __sb = new StringBuilder("NtfSangcharimHan(");
      bool __first = true;
      if (__isset.han) {
        if(!__first) { __sb.Append(", "); }
        __first = false;
        __sb.Append("Han: ");
        __sb.Append(Han);
      }
      __sb.Append(")");
      return __sb.ToString();
    }

  }

}
