/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;
using System.IO;
using Thrift;
using Thrift.Collections;
using System.Runtime.Serialization;
using Thrift.Protocol;
using Thrift.Transport;

namespace jangi
{

  #if !SILVERLIGHT
  [Serializable]
  #endif
  public partial class ReqLogin : TBase
  {
    private string _userName;
    private string _loginPlatform;
    private string _deviceDesc;

    public string UserName
    {
      get
      {
        return _userName;
      }
      set
      {
        __isset.userName = true;
        this._userName = value;
      }
    }

    public string LoginPlatform
    {
      get
      {
        return _loginPlatform;
      }
      set
      {
        __isset.loginPlatform = true;
        this._loginPlatform = value;
      }
    }

    public string DeviceDesc
    {
      get
      {
        return _deviceDesc;
      }
      set
      {
        __isset.deviceDesc = true;
        this._deviceDesc = value;
      }
    }


    public Isset __isset;
    #if !SILVERLIGHT
    [Serializable]
    #endif
    public struct Isset {
      public bool userName;
      public bool loginPlatform;
      public bool deviceDesc;
    }

    public ReqLogin() {
    }

    public void Read (TProtocol iprot)
    {
      iprot.IncrementRecursionDepth();
      try
      {
        TField field;
        iprot.ReadStructBegin();
        while (true)
        {
          field = iprot.ReadFieldBegin();
          if (field.Type == TType.Stop) { 
            break;
          }
          switch (field.ID)
          {
            case 1:
              if (field.Type == TType.String) {
                UserName = iprot.ReadString();
              } else { 
                TProtocolUtil.Skip(iprot, field.Type);
              }
              break;
            case 2:
              if (field.Type == TType.String) {
                LoginPlatform = iprot.ReadString();
              } else { 
                TProtocolUtil.Skip(iprot, field.Type);
              }
              break;
            case 3:
              if (field.Type == TType.String) {
                DeviceDesc = iprot.ReadString();
              } else { 
                TProtocolUtil.Skip(iprot, field.Type);
              }
              break;
            default: 
              TProtocolUtil.Skip(iprot, field.Type);
              break;
          }
          iprot.ReadFieldEnd();
        }
        iprot.ReadStructEnd();
      }
      finally
      {
        iprot.DecrementRecursionDepth();
      }
    }

    public void Write(TProtocol oprot) {
      oprot.IncrementRecursionDepth();
      try
      {
        TStruct struc = new TStruct("ReqLogin");
        oprot.WriteStructBegin(struc);
        TField field = new TField();
        if (UserName != null && __isset.userName) {
          field.Name = "userName";
          field.Type = TType.String;
          field.ID = 1;
          oprot.WriteFieldBegin(field);
          oprot.WriteString(UserName);
          oprot.WriteFieldEnd();
        }
        if (LoginPlatform != null && __isset.loginPlatform) {
          field.Name = "loginPlatform";
          field.Type = TType.String;
          field.ID = 2;
          oprot.WriteFieldBegin(field);
          oprot.WriteString(LoginPlatform);
          oprot.WriteFieldEnd();
        }
        if (DeviceDesc != null && __isset.deviceDesc) {
          field.Name = "deviceDesc";
          field.Type = TType.String;
          field.ID = 3;
          oprot.WriteFieldBegin(field);
          oprot.WriteString(DeviceDesc);
          oprot.WriteFieldEnd();
        }
        oprot.WriteFieldStop();
        oprot.WriteStructEnd();
      }
      finally
      {
        oprot.DecrementRecursionDepth();
      }
    }

    public override string ToString() {
      StringBuilder __sb = new StringBuilder("ReqLogin(");
      bool __first = true;
      if (UserName != null && __isset.userName) {
        if(!__first) { __sb.Append(", "); }
        __first = false;
        __sb.Append("UserName: ");
        __sb.Append(UserName);
      }
      if (LoginPlatform != null && __isset.loginPlatform) {
        if(!__first) { __sb.Append(", "); }
        __first = false;
        __sb.Append("LoginPlatform: ");
        __sb.Append(LoginPlatform);
      }
      if (DeviceDesc != null && __isset.deviceDesc) {
        if(!__first) { __sb.Append(", "); }
        __first = false;
        __sb.Append("DeviceDesc: ");
        __sb.Append(DeviceDesc);
      }
      __sb.Append(")");
      return __sb.ToString();
    }

  }

}
