/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */

namespace jangi
{
  public enum Sangcharim
  {
    kUnknown = 0,
    kSMSM = 1,
    kMSMS = 2,
    kMSSM = 3,
    kSMMS = 4,
  }
}
