/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;
using System.IO;
using Thrift;
using Thrift.Collections;
using System.Runtime.Serialization;
using Thrift.Protocol;
using Thrift.Transport;

namespace jangi
{

  #if !SILVERLIGHT
  [Serializable]
  #endif
  public partial class UserInfo : TBase
  {
    private string _nickName;
    private int _level;
    private int _victoryCount;
    private int _defeatCount;

    public string NickName
    {
      get
      {
        return _nickName;
      }
      set
      {
        __isset.nickName = true;
        this._nickName = value;
      }
    }

    public int Level
    {
      get
      {
        return _level;
      }
      set
      {
        __isset.level = true;
        this._level = value;
      }
    }

    public int VictoryCount
    {
      get
      {
        return _victoryCount;
      }
      set
      {
        __isset.victoryCount = true;
        this._victoryCount = value;
      }
    }

    public int DefeatCount
    {
      get
      {
        return _defeatCount;
      }
      set
      {
        __isset.defeatCount = true;
        this._defeatCount = value;
      }
    }


    public Isset __isset;
    #if !SILVERLIGHT
    [Serializable]
    #endif
    public struct Isset {
      public bool nickName;
      public bool level;
      public bool victoryCount;
      public bool defeatCount;
    }

    public UserInfo() {
    }

    public void Read (TProtocol iprot)
    {
      iprot.IncrementRecursionDepth();
      try
      {
        TField field;
        iprot.ReadStructBegin();
        while (true)
        {
          field = iprot.ReadFieldBegin();
          if (field.Type == TType.Stop) { 
            break;
          }
          switch (field.ID)
          {
            case 1:
              if (field.Type == TType.String) {
                NickName = iprot.ReadString();
              } else { 
                TProtocolUtil.Skip(iprot, field.Type);
              }
              break;
            case 2:
              if (field.Type == TType.I32) {
                Level = iprot.ReadI32();
              } else { 
                TProtocolUtil.Skip(iprot, field.Type);
              }
              break;
            case 3:
              if (field.Type == TType.I32) {
                VictoryCount = iprot.ReadI32();
              } else { 
                TProtocolUtil.Skip(iprot, field.Type);
              }
              break;
            case 4:
              if (field.Type == TType.I32) {
                DefeatCount = iprot.ReadI32();
              } else { 
                TProtocolUtil.Skip(iprot, field.Type);
              }
              break;
            default: 
              TProtocolUtil.Skip(iprot, field.Type);
              break;
          }
          iprot.ReadFieldEnd();
        }
        iprot.ReadStructEnd();
      }
      finally
      {
        iprot.DecrementRecursionDepth();
      }
    }

    public void Write(TProtocol oprot) {
      oprot.IncrementRecursionDepth();
      try
      {
        TStruct struc = new TStruct("UserInfo");
        oprot.WriteStructBegin(struc);
        TField field = new TField();
        if (NickName != null && __isset.nickName) {
          field.Name = "nickName";
          field.Type = TType.String;
          field.ID = 1;
          oprot.WriteFieldBegin(field);
          oprot.WriteString(NickName);
          oprot.WriteFieldEnd();
        }
        if (__isset.level) {
          field.Name = "level";
          field.Type = TType.I32;
          field.ID = 2;
          oprot.WriteFieldBegin(field);
          oprot.WriteI32(Level);
          oprot.WriteFieldEnd();
        }
        if (__isset.victoryCount) {
          field.Name = "victoryCount";
          field.Type = TType.I32;
          field.ID = 3;
          oprot.WriteFieldBegin(field);
          oprot.WriteI32(VictoryCount);
          oprot.WriteFieldEnd();
        }
        if (__isset.defeatCount) {
          field.Name = "defeatCount";
          field.Type = TType.I32;
          field.ID = 4;
          oprot.WriteFieldBegin(field);
          oprot.WriteI32(DefeatCount);
          oprot.WriteFieldEnd();
        }
        oprot.WriteFieldStop();
        oprot.WriteStructEnd();
      }
      finally
      {
        oprot.DecrementRecursionDepth();
      }
    }

    public override string ToString() {
      StringBuilder __sb = new StringBuilder("UserInfo(");
      bool __first = true;
      if (NickName != null && __isset.nickName) {
        if(!__first) { __sb.Append(", "); }
        __first = false;
        __sb.Append("NickName: ");
        __sb.Append(NickName);
      }
      if (__isset.level) {
        if(!__first) { __sb.Append(", "); }
        __first = false;
        __sb.Append("Level: ");
        __sb.Append(Level);
      }
      if (__isset.victoryCount) {
        if(!__first) { __sb.Append(", "); }
        __first = false;
        __sb.Append("VictoryCount: ");
        __sb.Append(VictoryCount);
      }
      if (__isset.defeatCount) {
        if(!__first) { __sb.Append(", "); }
        __first = false;
        __sb.Append("DefeatCount: ");
        __sb.Append(DefeatCount);
      }
      __sb.Append(")");
      return __sb.ToString();
    }

  }

}
