/**
 * Autogenerated by Thrift Compiler (0.9.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */

namespace jcasino
{
  public enum SevenCardStudBetType
  {
    kUnknown = 0,
    kDie = 1,
    kPping = 2,
    kTadang = 3,
    kCall = 4,
    kCheck = 5,
    kQuater = 6,
    kHalf = 7,
  }
}
