/**
 * Autogenerated by Thrift Compiler (0.9.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */

namespace jcasino
{
  public enum SevenCardStudHand
  {
    kUnknown = 0,
    kTop = 1,
    kOnePair = 2,
    kTwoPair = 3,
    kThreeCard = 4,
    Straight = 5,
    Mountain = 6,
    Flush = 7,
    Fullhouse = 8,
    FourCard = 9,
    RoyalStraightFlush = 10,
  }
}
