/**
 * Autogenerated by Thrift Compiler (0.9.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "jangi_constants.h"

namespace jangi {

const jangiConstants g_jangi_constants;

jangiConstants::jangiConstants() {
}

} // namespace

