/**
 * Autogenerated by Thrift Compiler (0.9.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef jangi_CONSTANTS_H
#define jangi_CONSTANTS_H

#include "jangi_types.h"

namespace jangi {

class jangiConstants {
 public:
  jangiConstants();

};

extern const jangiConstants g_jangi_constants;

} // namespace

#endif
