/**
 * Autogenerated by Thrift Compiler (0.9.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef test_TYPES_H
#define test_TYPES_H

#include <iosfwd>

#include <thrift/Thrift.h>
#include <thrift/TApplicationException.h>
#include <thrift/protocol/TProtocol.h>
#include <thrift/transport/TTransport.h>

#include <thrift/cxxfunctional.h>




class TestStruct1;

typedef struct _TestStruct1__isset {
  _TestStruct1__isset() : id(false), userName(false) {}
  bool id :1;
  bool userName :1;
} _TestStruct1__isset;

class TestStruct1 {
 public:

  static const char* ascii_fingerprint; // = "3F5FC93B338687BC7235B1AB103F47B3";
  static const uint8_t binary_fingerprint[16]; // = {0x3F,0x5F,0xC9,0x3B,0x33,0x86,0x87,0xBC,0x72,0x35,0xB1,0xAB,0x10,0x3F,0x47,0xB3};

  TestStruct1(const TestStruct1&);
  TestStruct1& operator=(const TestStruct1&);
  TestStruct1() : id(0), userName() {
  }

  virtual ~TestStruct1() throw();
  int32_t id;
  std::string userName;

  _TestStruct1__isset __isset;

  void __set_id(const int32_t val);

  void __set_userName(const std::string& val);

  bool operator == (const TestStruct1 & rhs) const
  {
    if (!(id == rhs.id))
      return false;
    if (!(userName == rhs.userName))
      return false;
    return true;
  }
  bool operator != (const TestStruct1 &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const TestStruct1 & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

  friend std::ostream& operator<<(std::ostream& out, const TestStruct1& obj);
};

void swap(TestStruct1 &a, TestStruct1 &b);



#endif
