/**
 * Autogenerated by Thrift Compiler (0.9.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "test_types.h"

#include <algorithm>
#include <ostream>

#include <thrift/TToString.h>




TestStruct1::~TestStruct1() throw() {
}


void TestStruct1::__set_id(const int32_t val) {
  this->id = val;
}

void TestStruct1::__set_userName(const std::string& val) {
  this->userName = val;
}

const char* TestStruct1::ascii_fingerprint = "3F5FC93B338687BC7235B1AB103F47B3";
const uint8_t TestStruct1::binary_fingerprint[16] = {0x3F,0x5F,0xC9,0x3B,0x33,0x86,0x87,0xBC,0x72,0x35,0xB1,0xAB,0x10,0x3F,0x47,0xB3};

uint32_t TestStruct1::read(::apache::thrift::protocol::TProtocol* iprot) {

  uint32_t xfer = 0;
  std::string fname;
  ::apache::thrift::protocol::TType ftype;
  int16_t fid;

  xfer += iprot->readStructBegin(fname);

  using ::apache::thrift::protocol::TProtocolException;


  while (true)
  {
    xfer += iprot->readFieldBegin(fname, ftype, fid);
    if (ftype == ::apache::thrift::protocol::T_STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
        if (ftype == ::apache::thrift::protocol::T_I32) {
          xfer += iprot->readI32(this->id);
          this->__isset.id = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 2:
        if (ftype == ::apache::thrift::protocol::T_STRING) {
          xfer += iprot->readString(this->userName);
          this->__isset.userName = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      default:
        xfer += iprot->skip(ftype);
        break;
    }
    xfer += iprot->readFieldEnd();
  }

  xfer += iprot->readStructEnd();

  return xfer;
}

uint32_t TestStruct1::write(::apache::thrift::protocol::TProtocol* oprot) const {
  uint32_t xfer = 0;
  oprot->incrementRecursionDepth();
  xfer += oprot->writeStructBegin("TestStruct1");

  xfer += oprot->writeFieldBegin("id", ::apache::thrift::protocol::T_I32, 1);
  xfer += oprot->writeI32(this->id);
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldBegin("userName", ::apache::thrift::protocol::T_STRING, 2);
  xfer += oprot->writeString(this->userName);
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldStop();
  xfer += oprot->writeStructEnd();
  oprot->decrementRecursionDepth();
  return xfer;
}

void swap(TestStruct1 &a, TestStruct1 &b) {
  using ::std::swap;
  swap(a.id, b.id);
  swap(a.userName, b.userName);
  swap(a.__isset, b.__isset);
}

TestStruct1::TestStruct1(const TestStruct1& other0) {
  id = other0.id;
  userName = other0.userName;
  __isset = other0.__isset;
}
TestStruct1& TestStruct1::operator=(const TestStruct1& other1) {
  id = other1.id;
  userName = other1.userName;
  __isset = other1.__isset;
  return *this;
}
std::ostream& operator<<(std::ostream& out, const TestStruct1& obj) {
  using apache::thrift::to_string;
  out << "TestStruct1(";
  out << "id=" << to_string(obj.id);
  out << ", " << "userName=" << to_string(obj.userName);
  out << ")";
  return out;
}


